### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by milkice233** [milkice233/efb-qq-slave#4]
- [ ] [酷Q] 当用户接收到好友名片时，支持直接从 Telegram 添加好友 (qq_contact_wrapper)
- [ ] [酷Q] 实现语音收发，如果暂时不支持语音的话向 EFM 发送消息告知用户收到一条语音
- [ ] [酷Q] 富文本(rich)消息支持（暂时未能成功复现富文本，因而处理富文本消息时会爆exception）
- [ ] [酷Q] 对于音乐分享类消息，适配更多音乐分享类消息（需要更多样例）
- [ ] [EQS] 加上漏加的 版本信息
- [ ] [EQS] 在at消息中，若at的人并不是用户自身同时也不是at全体用户，则将 @blahblah 的超链接设置为可以被用户点击打开并跳转到相应QQ Chat的形式（表述不清= =）
- [ ] [酷Q] 回复他人的消息会触发原消息引用，实现原消息内容截断功能（防止原消息过长导致的刷屏）

自己留着备忘，当然同时欢迎 contribution
